"""add tokenblacklist

Revision ID: 9ada47bf5382
Revises: 
Create Date: 2026-07-23 16:55:56.321413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ada47bf5382'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenblacklist_expires_at'), table_name='tokenblacklist')
    op.drop_index(op.f('ix_tokenblacklist_jti'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.add_column('chatmessage', sa.Column('user_role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole', native_enum=False), nullable=False))
    op.drop_index(op.f('idx_chatmessage_session'), table_name='chatmessage')
    op.drop_column('chatmessage', 'role')
    op.drop_index(op.f('idx_favorite_place'), table_name='favorite')
    op.drop_index(op.f('idx_itineraryitem_itin'), table_name='itineraryitem')
    op.alter_column('place', 'ward',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('place', 'link_google_map',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('place', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('place', 'opening_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('place', 'closing_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('place', 'open_days',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('place', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'CLOSED', 'PENDING', name='placestatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.drop_index(op.f('idx_place_district'), table_name='place')
    op.drop_index(op.f('idx_place_name_search'), table_name='place', postgresql_using='gin')
    op.drop_index(op.f('idx_place_rating'), table_name='place')
    op.drop_index(op.f('idx_place_status'), table_name='place')
    op.alter_column('placeagegroup', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('placeagegroup', 'age_group',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CHILDREN', 'TEENAGER', 'YOUNG_ADULT', 'ADULT', 'MIDDLE_AGE', 'SENIOR', name='agegroup', native_enum=False),
               existing_nullable=False)
    op.drop_constraint(op.f('placeagegroup_place_id_age_group_key'), 'placeagegroup', type_='unique')
    op.drop_index(op.f('idx_placeembedding_vector'), table_name='placeembedding', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('placeimage', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_one_primary_image'), table_name='placeimage', postgresql_where='(is_primary = true)')
    op.alter_column('review', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='reviewstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'APPROVED'::character varying"))
    op.drop_index(op.f('idx_review_place'), table_name='review')
    op.drop_index(op.f('idx_review_user'), table_name='review')
    op.alter_column('reviewembedding', 'chunk_index',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_reviewembedding_vector'), table_name='reviewembedding', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False),
               existing_nullable=False)
    op.alter_column('users', 'user_role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ADMIN', 'USER', name='userrole', native_enum=False),
               nullable=True,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('usertravelprofile', 'travel_style',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('SOLO', 'COUPLE', 'FAMILY', 'GROUP', name='travelstyle', native_enum=False),
               existing_nullable=True)
    op.alter_column('usertravelprofile', 'budget_level',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='budgetlevel', native_enum=False),
               existing_nullable=True)
    op.alter_column('visitedplace', 'source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MANUAL', name='visitedplacesource', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.drop_index(op.f('idx_visitedplace_user'), table_name='visitedplace')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_visitedplace_user'), 'visitedplace', ['user_id'], unique=False)
    op.alter_column('visitedplace', 'source',
               existing_type=sa.Enum('MANUAL', name='visitedplacesource', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.alter_column('usertravelprofile', 'budget_level',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='budgetlevel', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('usertravelprofile', 'travel_style',
               existing_type=sa.Enum('SOLO', 'COUPLE', 'FAMILY', 'GROUP', name='travelstyle', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('users', 'user_role',
               existing_type=sa.Enum('ADMIN', 'USER', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'USER'::character varying"))
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.create_index(op.f('idx_reviewembedding_vector'), 'reviewembedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('reviewembedding', 'chunk_index',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_review_user'), 'review', ['user_id'], unique=False)
    op.create_index(op.f('idx_review_place'), 'review', ['place_id'], unique=False)
    op.alter_column('review', 'status',
               existing_type=sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='reviewstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'APPROVED'::character varying"))
    op.create_index(op.f('idx_one_primary_image'), 'placeimage', ['place_id'], unique=True, postgresql_where='(is_primary = true)')
    op.alter_column('placeimage', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('idx_placeembedding_vector'), 'placeembedding', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_unique_constraint(op.f('placeagegroup_place_id_age_group_key'), 'placeagegroup', ['place_id', 'age_group'], postgresql_nulls_not_distinct=False)
    op.alter_column('placeagegroup', 'age_group',
               existing_type=sa.Enum('CHILDREN', 'TEENAGER', 'YOUNG_ADULT', 'ADULT', 'MIDDLE_AGE', 'SENIOR', name='agegroup', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('placeagegroup', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('idx_place_status'), 'place', ['status'], unique=False)
    op.create_index(op.f('idx_place_rating'), 'place', [sa.literal_column('average_rating DESC')], unique=False)
    op.create_index(op.f('idx_place_name_search'), 'place', [sa.literal_column("to_tsvector('simple'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_place_district'), 'place', ['district'], unique=False)
    op.alter_column('place', 'status',
               existing_type=sa.Enum('ACTIVE', 'CLOSED', 'PENDING', name='placestatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('place', 'open_days',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('place', 'closing_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('place', 'opening_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('place', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('place', 'link_google_map',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('place', 'ward',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('idx_itineraryitem_itin'), 'itineraryitem', ['itinerary_id'], unique=False)
    op.create_index(op.f('idx_favorite_place'), 'favorite', ['place_id'], unique=False)
    op.add_column('chatmessage', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_chatmessage_session'), 'chatmessage', ['session_id', 'created_at'], unique=False)
    op.drop_column('chatmessage', 'user_role')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.create_table('tokenblacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tokenblacklist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tokenblacklist_pkey')),
    sa.UniqueConstraint('jti', name=op.f('tokenblacklist_jti_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tokenblacklist_jti'), 'tokenblacklist', ['jti'], unique=False)
    op.create_index(op.f('ix_tokenblacklist_expires_at'), 'tokenblacklist', ['expires_at'], unique=False)
    # ### end Alembic commands ###
