"""add tokenblacklist

Revision ID: c2cab0a4fb2b
Revises: 9ada47bf5382
Create Date: 2026-07-23 17:00:45.945864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2cab0a4fb2b'
down_revision: Union[str, Sequence[str], None] = '9ada47bf5382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tokenblacklist_expires_at', 'tokenblacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tokenblacklist_jti'), 'tokenblacklist', ['jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokenblacklist_jti'), table_name='tokenblacklist')
    op.drop_index('ix_tokenblacklist_expires_at', table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###
